spring:
  application:
    name: hibernate-search
  thymeleaf:
    #mode: LEGACYHTML5
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://10.1.1.86:3306/aukey_wish_crawler?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: wish_crawler
    password: crawler2017
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8033
